### ISSUE TITLE
View distance is hard locked to 1600M

### ISSUE THREAD

**Issue by hunt103** [Bradenm1/Evannex#1]
So I host the mission on a dedicated server for a few friends of mine but it's almost impossible to effectively fly CAS as the view distance is far too short. Sometimes when I back out to lobby and change it on a non-dedicated server, it'll keep but if I adjust any video settings it reverts back to 1600.

**Comment by Bradenm1** [comment]
I'll look into this now. I've never tested dedicated server. I assume something is missing in the settings.

**Comment by Bradenm1** [comment]
Are you changing the 'ViewDistance' parameter on the dedicated server? It defaults to 1600.
